include: '.gitlab/ci-templates/docker_credentials.yml'

stages:
  - build

.build_service_intermediate_template: &build_template_intermediate
  stage: build
  tags:
    - docker
  image: docker:20.10.21
  script:
    - echo "Testing docker login"
  allow_failure: false

build_service:
  <<: *build_template_intermediate
  stage: build