version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    ports:
      - target: 5432
        published: 5433
        mode: host
    volumes:
      - ./app/todo-manager-backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: db_controller
      POSTGRES_PASSWORD:  postgres
      POSTGRES_DB: todo-manager
    networks:
      - todo-manager
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - target: 80
        published: 16543
        mode: host
    networks:
      - todo-manager
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./app/todo-manager-backend/database/servers.json:/pgadmin4/servers.json
      - ./app/todo-manager-backend/database/devdbypass:/pgadmin4/devdbpass
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: git-registry.thm.de/etmn59/todo-manager/ci-cd-pipeline/frontend:latest
    ports:
    - target: 4200
      published: 4200
      mode: host
    networks:
      - todo-manager
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  discovery-service:
    image: git-registry.thm.de/etmn59/todo-manager/ci-cd-pipeline/discovery-service:latest
    ports:
      - target: 8761
        published: 8761
        mode: host
    networks:
      - todo-manager
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  authentication-service:
    image: git-registry.thm.de/etmn59/todo-manager/ci-cd-pipeline/authentication-service:latest
    ports:
      - target: 8081
        published: 8081
        mode: host
    networks:
      - todo-manager
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  database-service:
    image: git-registry.thm.de/etmn59/todo-manager/ci-cd-pipeline/database-service:latest
    ports:
      - target: 8082
        published: 8082
        mode: host
    networks:
      - todo-manager
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  task-service:
    image: git-registry.thm.de/etmn59/todo-manager/ci-cd-pipeline/task-service:latest
    ports:
      - target: 8083
        published: 8083
        mode: host
    networks:
      - todo-manager
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  gateway-service:
    image: git-registry.thm.de/etmn59/todo-manager/ci-cd-pipeline/gateway-service:latest
    networks:
      - todo-manager
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  pgadmin_servers:
  pgadmin_devdbpass:
  db_data:

networks:
  todo-manager:
    driver: overlay
    external: true